import React, {useState} from 'react'
import withAuth from '../../hoc/withAuth';
import { PatternCardProps } from '../../types';

const PatternCard: React.FC<PatternCardProps> = ({ loggedInExpert, openModal, patternData }) => {
    const autoTag = patternData.isAutoGenerated ? 'Automation' : "Manual"
    let name = loggedInExpert === patternData.createdByExpertId ? 'You' : patternData.expertName 
    const inputDate = new Date(patternData.createdAt);
    const options: Intl.DateTimeFormatOptions = { year: 'numeric', month: 'long', day: 'numeric' };
    const formattedDate: string = inputDate.toLocaleDateString('en-US', options);
    const tagText = patternData.phaseText === "In Progress" ? "In Progress" : "Verified"
    const [elemText, setElemText] = useState(tagText);
    const handleHoverText = () => {
        setElemText(patternData.hoverText);
    };
    const handleMouseLeave = () => {
        setElemText(tagText);
    };
    const getBgColorClass = patternData.phaseColor ==="#F9C32F" ? "bg-[#F9C32F]" : patternData.phaseColor==="#E6321D" ? "bg-[#E6321D]" : "bg-[#538D3F]" ;

  return (
    <div className={`md:col-span-1 shadow-xl py-1 rounded-xl bg-white mt-4`} id="pattern-card" key={patternData.id}>
        <div className='flex justify-between mt-2'>
          <h1 className={`py-1 px-3 text-xl`}>{patternData.patternType}</h1>
          <div className='flex'>
          <div className={`flex items-center mx-3 px-3 rounded-2xl ${getBgColorClass}`} onMouseOver={handleHoverText} onMouseLeave={handleMouseLeave}>
            <p className={`text-white`}>{elemText}</p>
          </div>
          </div>
        </div>
        <div className='flex justify-between my-2'>
        <div className={`flex items-center mx-3 px-3 rounded-2xl bg-[#805DA8]`}>
            <p className={`text-white`}>{autoTag}</p>
          </div>
          {patternData.isAutoGenerated===true ? <p className='text-gray-400 px-3 italic font-serif '>Created By : AI Model</p> : <p className='text-gray-400 px-3 italic font-serif '>Created By : {name}</p> }
        </div>
        <div className='flex justify-between py-1 px-3 my-2'>
          <button className={`px-8 py-1 bg-blue-500 rounded-lg shadow-lg text-white`} onClick={openModal}>View Details</button>
          <p className='italic font-serif text-gray-400'>{formattedDate}</p>
        </div>
    </div>
  )
}

export default withAuth(PatternCard)