import React, {useState} from 'react'
import withAuth from '../../hoc/withAuth';
import { PatternCardProps } from '../../types';
import { Carousel } from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css';

const PatternCard: React.FC<PatternCardProps> = ({ loggedInExpert, openModal, patternData, z_index }) => {
    const autoTag = patternData.isAutoGenerated ? 'Automation' : "Manual"
    let name = loggedInExpert === patternData.createdByExpertId ? 'You' : patternData.expertName 
    const inputDate = new Date(patternData.createdAt);
    const options: Intl.DateTimeFormatOptions = { year: 'numeric', month: 'long', day: 'numeric' };
    const formattedDate: string = inputDate.toLocaleDateString('en-US', options);
    const tagText = patternData.phaseText === "In Progress" ? "In Progress" : "Verified"
    const [elemText, setElemText] = useState(tagText);
    const handleHoverText = () => {
        setElemText(patternData.hoverText);
    };
    const handleMouseLeave = () => {
        setElemText(tagText);
    };
    const getBgColorClass = patternData.phaseColor ==="#F9C32F" ? "bg-[#F9C32F]" : patternData.phaseColor==="#E6321D" ? "bg-[#E6321D]" : "bg-[#538D3F]" ;

  return (
    <div className={`col-span-1 py-1 rounded-xl bg-white mt-4 ${z_index}`} id="pattern-card" key={patternData.id}>
      <div className='flex items-center justify-between mt-2 px-3'>
        <h1 className={`text-lg sm:text-xl`}>{patternData.patternType}</h1>
        <div className='flex justify-between py-1 my-2'>
          <button className={`px-8 py-1 bg-blue-500 rounded-lg shadow-lg text-white`} onClick={openModal}>View Details</button>
        </div>
      </div>
      <div className='flex justify-between my-2 px-3'>
        {patternData.isAutoGenerated===true ? <p className='text-gray-400 italic font-serif '>Created By : AI Model</p> : <p className='text-gray-400 italic font-serif '>Created By : {name}</p> }
        <div className='flex'>
          <p className='italic font-serif text-gray-400'>{formattedDate}</p>
        </div>
      </div>
      <div className={`w-full h-auto`}>
        <Carousel showThumbs={false} showStatus={false} infiniteLoop={true} autoPlay={false} interval={3000} className='sm:py-4'>
          {patternData.patternImageUrls.map((img)=>(
            <div className="w-full p-4 lg:p-8 bg-gray-200">
              <img src={img} alt='pattern snapshots'/>
            </div>
          ))}
        </Carousel>
      </div>
    </div>
  )
}

export default withAuth(PatternCard)